apiVersion: v1
kind: Service
metadata:
  name: my-pythonapp-service
  namespace: python-ns
spec:
  selector:
    app: my-pythonapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8189
  type: NodePort
